version: '3'
services:
  tokped-play-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: tokped-play-api
    container_name: tokped-play-api
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_URL=$DATABASE_URL
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - app-network
  db:
    build: ./mongodb-rs
    container_name: db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin 
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=db
      - MONGO_REPLICA_HOST=localhost
      - MONGO_REPLICA_PORT=27017
    ports:
      - "27017:27017"
    volumes:     
      - dbdata:/data/db
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules: